# Generated by Django 5.1.7 on 2025-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_jobslotaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='employersubscription',
            name='job_limit',
            field=models.IntegerField(default=0, help_text='Employer-specific job limit'),
        ),
        migrations.AlterField(
            model_name='employersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
