# Generated by Django 5.1.7 on 2025-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('You missed', 'You missed'), ('Canceled', 'Canceled'), ('Upcoming', 'Upcoming'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Upcoming', max_length=20),
        ),
    ]
