# Generated by Django 5.1.7 on 2025-04-15 00:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0004_alter_applyedjobs_status'),
        ('Interview', '0002_alter_interviewshedule_status'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewshedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewshedule',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interviewshedule',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.candidate'),
        ),
        migrations.AlterField(
            model_name='interviewshedule',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.employer'),
        ),
        migrations.AlterField(
            model_name='interviewshedule',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empjob.jobs'),
        ),
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Selected', 'Selected'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected'), ('You missed', 'You missed')], default='Upcoming', max_length=20),
        ),
    ]
