# Generated by Django 5.1.7 on 2025-04-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
