# Generated by Django 5.1.7 on 2025-04-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_file_url'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chatroom',
            field=models.ForeignKey(help_text='The chat room this message belongs to.', on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file_url',
            field=models.CharField(blank=True, help_text='URL of any attached media file (e.g., image, video).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates if the message has been read by the recipient.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_send',
            field=models.BooleanField(default=False, help_text='Indicates if the message has been successfully sent.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, default='', help_text='The text content of the message (optional if media is present).', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sendername',
            field=models.TextField(blank=True, help_text='Name of the sender (e.g., candidate or employer name).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was sent.'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='candidate',
            field=models.ForeignKey(help_text='The candidate participating in the chat.', on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='user_account.candidate'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the chat room was created.'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='employer',
            field=models.ForeignKey(help_text='The employer participating in the chat.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='user_account.employer'),
        ),
    ]
