# Generated by Django 5.1.7 on 2025-04-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('lpa', models.CharField(blank=True, max_length=20, null=True)),
                ('jobtype', models.CharField(blank=True, max_length=30, null=True)),
                ('jobmode', models.CharField(blank=True, max_length=30, null=True)),
                ('experience', models.CharField(max_length=50)),
                ('applyBefore', models.DateField(blank=True, null=True)),
                ('posteDate', models.DateTimeField(auto_now_add=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('industry', models.CharField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_jobs', to='user_account.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_requested', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='user_account.candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='user_account.employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='Empjob.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Text Answer'), ('MCQ', 'Multiple Choice'), ('CODE', 'Code Answer')], default='TEXT', max_length=4)),
                ('options', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Empjob.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='user_account.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Empjob.question')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Application Send', 'Application Send'), ('Application Viewd', 'Application Viewed'), ('Resume Viewd', 'Resume Viewed')], default='Application Send', max_length=20)),
                ('applyed_on', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empjob.jobs')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empjob.jobs')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
