# Generated by Django 5.1.7 on 2025-04-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
