# Generated by Django 5.1.7 on 2025-04-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0002_approvals_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
