# Generated by Django 5.1.7 on 2025-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empjob', '0003_answer_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyedjobs',
            name='status',
            field=models.CharField(choices=[('Application Send', 'Application Send'), ('Application Viewed', 'Application Viewed'), ('Resume Viewed', 'Resume Viewed'), ('Pending', 'Pending'), ('ShortListed', 'ShortListed'), ('Interview Scheduled', 'Interview Scheduled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Application Send', max_length=20),
        ),
    ]
